### PR TITLE
Update Dockerfile to enable change root context

### PR DESCRIPTION
**Pull request by gebing**
Update Dockerfile to enable change root context, and fix bug for "Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /src/app/index.php on line 157".

### CODE REVIEW

**Comment by erikdubbelboer** [comment]
Can you explain why you would want to change the root context?

**Comment by gebing** [comment]
i use phpRedisAdmin under a certain context path such as "https://my.domain/redis-admin/" and use AWS Elastic Load Balancer to forward request to phpRedisAdmin with context path "redis-admin".

**Comment by erikdubbelboer** [comment]
Can't AWS Elastic Load Balancer rewrite the path? All load balancers I know support this.

**Comment by gebing** [comment]
1. Even AWS Elastic Load Balancer rewrite the path from

**Comment by erikdubbelboer** [comment]
I think it's a bit weird to have to support a broken loadbalancer like that. I think it's better if you overwrite the entrypoint using `--entrypoint` or `command: ...` in docker-compose.

**Pull request closed without merging**
