### PR TITLE
Avoid unnecessary horizontal scrollbars

### PR DESCRIPTION
**Pull request by abraaoz**
Fix long key values rendering with horizontal scrollbar;
Fix keys folder with checkbox in one line and key name in another line.

### CODE REVIEW

**Comment by erikdubbelboer** [comment]
I'm curious, why do you think showing `...` is better than having a horizontal scroll bar for very long keys?

**Comment by abraaoz** [comment]
Hello Erik, you are right. In the case of long key names, the scrollbar is better. I put a title="..." to show the full key name when mouse over and fixed the scrollbar behavior for newer browsers.

**Comment by erikdubbelboer** [comment]
Can you please check this in Firefox as well. I'm not sure why but the padding on the right frame is gone in Firefox:

Screenshot 2020-02-23 at 10 16 08

**Comment by abraaoz** [comment]
I've tested in Firefox for Windows and the padding was not missing. Instead of padding inside the iframe, I changed to margin outside the iframe. Can you please test in your environment?

**Comment by erikdubbelboer** [comment]
Looks good, thanks!

**Pull request merged**
