### PR TITLE
Limit the max number of keys when scanning

### PR DESCRIPTION
**Pull request by LeoHsiao1**
Hi, glad to see you're still maintaining this 12 year old project!
Among the redis web GUI tools, phpRedisAdmin is still the most powerful one.

But now there is a serious problem: if the redis db contains more than 100,000 keys, it takes phpRedisAdmin tens of seconds to open the db, or even timeout.
I have a simple solution: limit the max number of keys when scanning.

For reference, AnotherRedisDesktopManager also has this limitation, and the max number is 500.
https://github.com/qishibo/AnotherRedisDesktopManager/blob/d373d653063c2a0c256c743777118b92231010ba/src/components/contents/KeyContentStream.vue#L199

### CODE REVIEW

**Review by erikdubbelboer — CHANGES_REQUESTED** [review]
Can you make it `scanmax` and add it here as well? https://github.com/erikdubbelboer/phpRedisAdmin/blob/master/includes/config.sample.inc.php#L35

**Comment by LeoHsiao1** [comment]
Sure. I added a line of comment.

**Comment by LeoHsiao1** [comment]
I have tested this and found that even if the redis db contains millions of keys, a query with `'scanmax' => 1000` takes less than 1 second.
A query with `'scanmax' => 5000` takes nearly 5 seconds.

**Comment by erikdubbelboer** [comment]
Thanks!

**Comment by GregOriol** [comment]
Wait, does this mean that the display will be incomplete, and that there is no mention about it anywhere to the user?

There is also no way to "load more"?

I agree with a need to limit issues when servers have a huge number of keys, but this solution is really problematic.

**Comment by LeoHsiao1** [comment]
In AnotherRedisDesktopManager, if the number of keys exceeds 500, it displays the "load more" button.
It would be nice to implement this feature in phpRedisAdmin, but it would require more code changes.

An alternative is to display a warning at the bottom of sidebar: "reached the limit"
I can try to add the warning.

**Comment by LeoHsiao1** [comment]
I came up with another solution that always shows the number of keys being scanned and the limit.
It is displayed like this:
screenshot-20240919-175419

**Comment by GregOriol** [comment]
Kind of better, but not sure it would be clear enough for users. I think some "keys limit reached" message should be clear, or a "more" button would make it more clear.

**Comment by LeoHsiao1** [comment]
Adding "load more" button is definitely better, but this project currently lacks contributors.
I've opened a new PR to make a small patch.

**Pull request merged**
